site_name: My Project Docs
theme:
  name: material
  features:
  - navigation.tabs
nav:
- Home: index.md
- Performance: Performance.md
- Readme: README.md
- Advantages: advantages.md
- Performance: performance.md
- Readme: readme.md
- Testing: testing.md
- Usage: usage.md
