site_name: My Project Docs
theme:
  name: material
  features:
  - navigation.tabs
nav:
- Home: index.md
- Testing: testing.md
- Child Docs:
  - Performance: child-repo/Performance.md
  - Advantages: child-repo/advantages.md
  - Contribution: child-repo/contribution.md
  - Newfile: child-repo/newfile.md
  - Readme: child-repo/readme.md
  - Testing: child-repo/testing.md
  - Usage: child-repo/usage.md
