site_name: My Project Docs
theme:
  name: material
  features:
  - navigation.tabs
nav:
- Testing: testing.md
- Readme: readme.md
- Performance: Performance.md
- Working: working.md
- Usage: usage.md
